name: Autograding Tests
'on':
- push
- workflow_dispatch
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Test 3
      id: test-3
      uses: education/autograding-command-grader@v1
      with:
        test-name: Test 3
        setup-command: pip install pytest
        command: pytest test_lecture6lab.py::test_part3
        timeout: 1
        max-score: 1
    - name: Test 2
      id: test-2
      uses: education/autograding-command-grader@v1
      with:
        test-name: Test 2
        setup-command: pip install pytest
        command: pytest test_lecture6lab.py::test_part2
        timeout: 1
        max-score: 1
    - name: Test 3
      id: test-3
      uses: education/autograding-command-grader@v1
      with:
        test-name: Test 3
        setup-command: pip install pytest
        command: pytest test_lecture6lab.py::test_part2
        timeout: 1
        max-score: 1
    - name: Test 4
      id: test-4
      uses: education/autograding-command-grader@v1
      with:
        test-name: Test 4
        setup-command: pip install pytest
        command: pytest test_lecture6lab.py::test_part4
        timeout: 1
        max-score: 1
    - name: Autograding Reporter
      uses: education/autograding-grading-reporter@v1
      env:
        TEST-3_RESULTS: "${{steps.test-3.outputs.result}}"
        TEST-2_RESULTS: "${{steps.test-2.outputs.result}}"
        TEST-4_RESULTS: "${{steps.test-4.outputs.result}}"
      with:
        runners: test-3,test-2,test-3,test-4
